TOP=..
include $(TOP)/configure/CONFIG
#=======================================
DB_INSTALLS += $(ASYN)/db/asynRecord.db
# Install .dbd and .db files
DB += cryosms.db
DATA += cryosms.proto

#=======================================
include $(TOP)/configure/RULES
